@default_files = ('paper.tex');

# generate pdf using xelatex
$pdf_mode = 5;

# clean .bbl files
$bibtex_use = 2;

# clean extra files
push @generated_exts, 'run.xml', 'xdv', 'synctex.gz';

$pdf_previewer = 'start zathura';
